name: Deploy Portfolio to Hostinger

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: Build Next.js & Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies & Build
        run: |
          npm ci
          npm run build
